[package]
name = "satpaper"
authors = ["Colonial"]
version = "0.5.0"
edition = "2021"

description = "Display near-real-time satellite imagery on your desktop."
repository = "https://github.com/Colonial-Dev/satpaper"
readme = "README.md"
license = "MIT OR Apache-2.0"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true

[dependencies]
# Runtime
anyhow = "1.0.75"
log = "0.4.20"
env_logger = "0.10.0"
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.2", features = ["derive", "env"] }
mimalloc = { version = "0.1.38", default-features = false }

# Compositing
bytes = "1.4.0"
image = "0.24.7"

# Scraping
reqwest = { version = "0.11.20", default_features = false, features = ["rustls-tls"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
