name: spacepaper
services:
  spacepaper:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - SPACEPAPER_SATELLITE=goes-east
      - SPACEPAPER_RESOLUTION_X=2560
      - SPACEPAPER_RESOLUTION_Y=1440
      - SPACEPAPER_DISK_SIZE=95
    volumes:
      - ../images:/home/rust/images