name: Cargo Comprehensive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
  
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - name: Build and test for Docker
      run: docker build -f docker/Dockerfile --target test .